version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: q_pal_app
    ports:
      - "8080:8080"
      - "2345:2345"
    tty: true
    volumes:
      - ./app:/app
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: q_pal_db
    environment:
      MYSQL_USER: qpal
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: q_pal_db
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
