// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// FavoriteStore is an object representing the database table.
type FavoriteStore struct {
	CustomerID    int       `boil:"customer_id" json:"customer_id" toml:"customer_id" yaml:"customer_id"`
	StoreID       int       `boil:"store_id" json:"store_id" toml:"store_id" yaml:"store_id"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedBy     null.Int  `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedByType string    `boil:"created_by_type" json:"created_by_type" toml:"created_by_type" yaml:"created_by_type"`
	UpdatedBy     null.Int  `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	UpdatedByType string    `boil:"updated_by_type" json:"updated_by_type" toml:"updated_by_type" yaml:"updated_by_type"`

	R *favoriteStoreR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L favoriteStoreL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FavoriteStoreColumns = struct {
	CustomerID    string
	StoreID       string
	CreatedAt     string
	UpdatedAt     string
	CreatedBy     string
	CreatedByType string
	UpdatedBy     string
	UpdatedByType string
}{
	CustomerID:    "customer_id",
	StoreID:       "store_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	CreatedBy:     "created_by",
	CreatedByType: "created_by_type",
	UpdatedBy:     "updated_by",
	UpdatedByType: "updated_by_type",
}

var FavoriteStoreTableColumns = struct {
	CustomerID    string
	StoreID       string
	CreatedAt     string
	UpdatedAt     string
	CreatedBy     string
	CreatedByType string
	UpdatedBy     string
	UpdatedByType string
}{
	CustomerID:    "favorite_stores.customer_id",
	StoreID:       "favorite_stores.store_id",
	CreatedAt:     "favorite_stores.created_at",
	UpdatedAt:     "favorite_stores.updated_at",
	CreatedBy:     "favorite_stores.created_by",
	CreatedByType: "favorite_stores.created_by_type",
	UpdatedBy:     "favorite_stores.updated_by",
	UpdatedByType: "favorite_stores.updated_by_type",
}

// Generated where

var FavoriteStoreWhere = struct {
	CustomerID    whereHelperint
	StoreID       whereHelperint
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	CreatedBy     whereHelpernull_Int
	CreatedByType whereHelperstring
	UpdatedBy     whereHelpernull_Int
	UpdatedByType whereHelperstring
}{
	CustomerID:    whereHelperint{field: "`favorite_stores`.`customer_id`"},
	StoreID:       whereHelperint{field: "`favorite_stores`.`store_id`"},
	CreatedAt:     whereHelpertime_Time{field: "`favorite_stores`.`created_at`"},
	UpdatedAt:     whereHelpertime_Time{field: "`favorite_stores`.`updated_at`"},
	CreatedBy:     whereHelpernull_Int{field: "`favorite_stores`.`created_by`"},
	CreatedByType: whereHelperstring{field: "`favorite_stores`.`created_by_type`"},
	UpdatedBy:     whereHelpernull_Int{field: "`favorite_stores`.`updated_by`"},
	UpdatedByType: whereHelperstring{field: "`favorite_stores`.`updated_by_type`"},
}

// FavoriteStoreRels is where relationship names are stored.
var FavoriteStoreRels = struct {
	Customer string
	Store    string
}{
	Customer: "Customer",
	Store:    "Store",
}

// favoriteStoreR is where relationships are stored.
type favoriteStoreR struct {
	Customer *Customer `boil:"Customer" json:"Customer" toml:"Customer" yaml:"Customer"`
	Store    *Store    `boil:"Store" json:"Store" toml:"Store" yaml:"Store"`
}

// NewStruct creates a new relationship struct
func (*favoriteStoreR) NewStruct() *favoriteStoreR {
	return &favoriteStoreR{}
}

func (r *favoriteStoreR) GetCustomer() *Customer {
	if r == nil {
		return nil
	}
	return r.Customer
}

func (r *favoriteStoreR) GetStore() *Store {
	if r == nil {
		return nil
	}
	return r.Store
}

// favoriteStoreL is where Load methods for each relationship are stored.
type favoriteStoreL struct{}

var (
	favoriteStoreAllColumns            = []string{"customer_id", "store_id", "created_at", "updated_at", "created_by", "created_by_type", "updated_by", "updated_by_type"}
	favoriteStoreColumnsWithoutDefault = []string{"customer_id", "store_id"}
	favoriteStoreColumnsWithDefault    = []string{"created_at", "updated_at", "created_by", "created_by_type", "updated_by", "updated_by_type"}
	favoriteStorePrimaryKeyColumns     = []string{"customer_id", "store_id"}
	favoriteStoreGeneratedColumns      = []string{}
)

type (
	// FavoriteStoreSlice is an alias for a slice of pointers to FavoriteStore.
	// This should almost always be used instead of []FavoriteStore.
	FavoriteStoreSlice []*FavoriteStore
	// FavoriteStoreHook is the signature for custom FavoriteStore hook methods
	FavoriteStoreHook func(context.Context, boil.ContextExecutor, *FavoriteStore) error

	favoriteStoreQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	favoriteStoreType                 = reflect.TypeOf(&FavoriteStore{})
	favoriteStoreMapping              = queries.MakeStructMapping(favoriteStoreType)
	favoriteStorePrimaryKeyMapping, _ = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, favoriteStorePrimaryKeyColumns)
	favoriteStoreInsertCacheMut       sync.RWMutex
	favoriteStoreInsertCache          = make(map[string]insertCache)
	favoriteStoreUpdateCacheMut       sync.RWMutex
	favoriteStoreUpdateCache          = make(map[string]updateCache)
	favoriteStoreUpsertCacheMut       sync.RWMutex
	favoriteStoreUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var favoriteStoreAfterSelectHooks []FavoriteStoreHook

var favoriteStoreBeforeInsertHooks []FavoriteStoreHook
var favoriteStoreAfterInsertHooks []FavoriteStoreHook

var favoriteStoreBeforeUpdateHooks []FavoriteStoreHook
var favoriteStoreAfterUpdateHooks []FavoriteStoreHook

var favoriteStoreBeforeDeleteHooks []FavoriteStoreHook
var favoriteStoreAfterDeleteHooks []FavoriteStoreHook

var favoriteStoreBeforeUpsertHooks []FavoriteStoreHook
var favoriteStoreAfterUpsertHooks []FavoriteStoreHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FavoriteStore) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FavoriteStore) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FavoriteStore) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FavoriteStore) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FavoriteStore) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FavoriteStore) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FavoriteStore) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FavoriteStore) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FavoriteStore) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range favoriteStoreAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFavoriteStoreHook registers your hook function for all future operations.
func AddFavoriteStoreHook(hookPoint boil.HookPoint, favoriteStoreHook FavoriteStoreHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		favoriteStoreAfterSelectHooks = append(favoriteStoreAfterSelectHooks, favoriteStoreHook)
	case boil.BeforeInsertHook:
		favoriteStoreBeforeInsertHooks = append(favoriteStoreBeforeInsertHooks, favoriteStoreHook)
	case boil.AfterInsertHook:
		favoriteStoreAfterInsertHooks = append(favoriteStoreAfterInsertHooks, favoriteStoreHook)
	case boil.BeforeUpdateHook:
		favoriteStoreBeforeUpdateHooks = append(favoriteStoreBeforeUpdateHooks, favoriteStoreHook)
	case boil.AfterUpdateHook:
		favoriteStoreAfterUpdateHooks = append(favoriteStoreAfterUpdateHooks, favoriteStoreHook)
	case boil.BeforeDeleteHook:
		favoriteStoreBeforeDeleteHooks = append(favoriteStoreBeforeDeleteHooks, favoriteStoreHook)
	case boil.AfterDeleteHook:
		favoriteStoreAfterDeleteHooks = append(favoriteStoreAfterDeleteHooks, favoriteStoreHook)
	case boil.BeforeUpsertHook:
		favoriteStoreBeforeUpsertHooks = append(favoriteStoreBeforeUpsertHooks, favoriteStoreHook)
	case boil.AfterUpsertHook:
		favoriteStoreAfterUpsertHooks = append(favoriteStoreAfterUpsertHooks, favoriteStoreHook)
	}
}

// OneG returns a single favoriteStore record from the query using the global executor.
func (q favoriteStoreQuery) OneG(ctx context.Context) (*FavoriteStore, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single favoriteStore record from the query.
func (q favoriteStoreQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FavoriteStore, error) {
	o := &FavoriteStore{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for favorite_stores")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all FavoriteStore records from the query using the global executor.
func (q favoriteStoreQuery) AllG(ctx context.Context) (FavoriteStoreSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all FavoriteStore records from the query.
func (q favoriteStoreQuery) All(ctx context.Context, exec boil.ContextExecutor) (FavoriteStoreSlice, error) {
	var o []*FavoriteStore

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to FavoriteStore slice")
	}

	if len(favoriteStoreAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all FavoriteStore records in the query using the global executor
func (q favoriteStoreQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all FavoriteStore records in the query.
func (q favoriteStoreQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count favorite_stores rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q favoriteStoreQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q favoriteStoreQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if favorite_stores exists")
	}

	return count > 0, nil
}

// Customer pointed to by the foreign key.
func (o *FavoriteStore) Customer(mods ...qm.QueryMod) customerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`customer_id` = ?", o.CustomerID),
	}

	queryMods = append(queryMods, mods...)

	return Customers(queryMods...)
}

// Store pointed to by the foreign key.
func (o *FavoriteStore) Store(mods ...qm.QueryMod) storeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`store_id` = ?", o.StoreID),
	}

	queryMods = append(queryMods, mods...)

	return Stores(queryMods...)
}

// LoadCustomer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (favoriteStoreL) LoadCustomer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFavoriteStore interface{}, mods queries.Applicator) error {
	var slice []*FavoriteStore
	var object *FavoriteStore

	if singular {
		var ok bool
		object, ok = maybeFavoriteStore.(*FavoriteStore)
		if !ok {
			object = new(FavoriteStore)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFavoriteStore)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFavoriteStore))
			}
		}
	} else {
		s, ok := maybeFavoriteStore.(*[]*FavoriteStore)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFavoriteStore)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFavoriteStore))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &favoriteStoreR{}
		}
		args = append(args, object.CustomerID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &favoriteStoreR{}
			}

			for _, a := range args {
				if a == obj.CustomerID {
					continue Outer
				}
			}

			args = append(args, obj.CustomerID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`customers`),
		qm.WhereIn(`customers.customer_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Customer")
	}

	var resultSlice []*Customer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Customer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for customers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for customers")
	}

	if len(customerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Customer = foreign
		if foreign.R == nil {
			foreign.R = &customerR{}
		}
		foreign.R.FavoriteStores = append(foreign.R.FavoriteStores, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CustomerID == foreign.CustomerID {
				local.R.Customer = foreign
				if foreign.R == nil {
					foreign.R = &customerR{}
				}
				foreign.R.FavoriteStores = append(foreign.R.FavoriteStores, local)
				break
			}
		}
	}

	return nil
}

// LoadStore allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (favoriteStoreL) LoadStore(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFavoriteStore interface{}, mods queries.Applicator) error {
	var slice []*FavoriteStore
	var object *FavoriteStore

	if singular {
		var ok bool
		object, ok = maybeFavoriteStore.(*FavoriteStore)
		if !ok {
			object = new(FavoriteStore)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFavoriteStore)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFavoriteStore))
			}
		}
	} else {
		s, ok := maybeFavoriteStore.(*[]*FavoriteStore)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFavoriteStore)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFavoriteStore))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &favoriteStoreR{}
		}
		args = append(args, object.StoreID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &favoriteStoreR{}
			}

			for _, a := range args {
				if a == obj.StoreID {
					continue Outer
				}
			}

			args = append(args, obj.StoreID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`stores`),
		qm.WhereIn(`stores.store_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Store")
	}

	var resultSlice []*Store
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Store")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for stores")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for stores")
	}

	if len(storeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Store = foreign
		if foreign.R == nil {
			foreign.R = &storeR{}
		}
		foreign.R.FavoriteStores = append(foreign.R.FavoriteStores, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StoreID == foreign.StoreID {
				local.R.Store = foreign
				if foreign.R == nil {
					foreign.R = &storeR{}
				}
				foreign.R.FavoriteStores = append(foreign.R.FavoriteStores, local)
				break
			}
		}
	}

	return nil
}

// SetCustomerG of the favoriteStore to the related item.
// Sets o.R.Customer to related.
// Adds o to related.R.FavoriteStores.
// Uses the global database handle.
func (o *FavoriteStore) SetCustomerG(ctx context.Context, insert bool, related *Customer) error {
	return o.SetCustomer(ctx, boil.GetContextDB(), insert, related)
}

// SetCustomer of the favoriteStore to the related item.
// Sets o.R.Customer to related.
// Adds o to related.R.FavoriteStores.
func (o *FavoriteStore) SetCustomer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Customer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `favorite_stores` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"customer_id"}),
		strmangle.WhereClause("`", "`", 0, favoriteStorePrimaryKeyColumns),
	)
	values := []interface{}{related.CustomerID, o.CustomerID, o.StoreID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CustomerID = related.CustomerID
	if o.R == nil {
		o.R = &favoriteStoreR{
			Customer: related,
		}
	} else {
		o.R.Customer = related
	}

	if related.R == nil {
		related.R = &customerR{
			FavoriteStores: FavoriteStoreSlice{o},
		}
	} else {
		related.R.FavoriteStores = append(related.R.FavoriteStores, o)
	}

	return nil
}

// SetStoreG of the favoriteStore to the related item.
// Sets o.R.Store to related.
// Adds o to related.R.FavoriteStores.
// Uses the global database handle.
func (o *FavoriteStore) SetStoreG(ctx context.Context, insert bool, related *Store) error {
	return o.SetStore(ctx, boil.GetContextDB(), insert, related)
}

// SetStore of the favoriteStore to the related item.
// Sets o.R.Store to related.
// Adds o to related.R.FavoriteStores.
func (o *FavoriteStore) SetStore(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Store) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `favorite_stores` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"store_id"}),
		strmangle.WhereClause("`", "`", 0, favoriteStorePrimaryKeyColumns),
	)
	values := []interface{}{related.StoreID, o.CustomerID, o.StoreID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StoreID = related.StoreID
	if o.R == nil {
		o.R = &favoriteStoreR{
			Store: related,
		}
	} else {
		o.R.Store = related
	}

	if related.R == nil {
		related.R = &storeR{
			FavoriteStores: FavoriteStoreSlice{o},
		}
	} else {
		related.R.FavoriteStores = append(related.R.FavoriteStores, o)
	}

	return nil
}

// FavoriteStores retrieves all the records using an executor.
func FavoriteStores(mods ...qm.QueryMod) favoriteStoreQuery {
	mods = append(mods, qm.From("`favorite_stores`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`favorite_stores`.*"})
	}

	return favoriteStoreQuery{q}
}

// FindFavoriteStoreG retrieves a single record by ID.
func FindFavoriteStoreG(ctx context.Context, customerID int, storeID int, selectCols ...string) (*FavoriteStore, error) {
	return FindFavoriteStore(ctx, boil.GetContextDB(), customerID, storeID, selectCols...)
}

// FindFavoriteStore retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFavoriteStore(ctx context.Context, exec boil.ContextExecutor, customerID int, storeID int, selectCols ...string) (*FavoriteStore, error) {
	favoriteStoreObj := &FavoriteStore{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `favorite_stores` where `customer_id`=? AND `store_id`=?", sel,
	)

	q := queries.Raw(query, customerID, storeID)

	err := q.Bind(ctx, exec, favoriteStoreObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from favorite_stores")
	}

	if err = favoriteStoreObj.doAfterSelectHooks(ctx, exec); err != nil {
		return favoriteStoreObj, err
	}

	return favoriteStoreObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *FavoriteStore) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FavoriteStore) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no favorite_stores provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(favoriteStoreColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	favoriteStoreInsertCacheMut.RLock()
	cache, cached := favoriteStoreInsertCache[key]
	favoriteStoreInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			favoriteStoreAllColumns,
			favoriteStoreColumnsWithDefault,
			favoriteStoreColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `favorite_stores` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `favorite_stores` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `favorite_stores` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, favoriteStorePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into favorite_stores")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.CustomerID,
		o.StoreID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for favorite_stores")
	}

CacheNoHooks:
	if !cached {
		favoriteStoreInsertCacheMut.Lock()
		favoriteStoreInsertCache[key] = cache
		favoriteStoreInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single FavoriteStore record using the global executor.
// See Update for more documentation.
func (o *FavoriteStore) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the FavoriteStore.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FavoriteStore) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	favoriteStoreUpdateCacheMut.RLock()
	cache, cached := favoriteStoreUpdateCache[key]
	favoriteStoreUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			favoriteStoreAllColumns,
			favoriteStorePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update favorite_stores, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `favorite_stores` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, favoriteStorePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, append(wl, favoriteStorePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update favorite_stores row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for favorite_stores")
	}

	if !cached {
		favoriteStoreUpdateCacheMut.Lock()
		favoriteStoreUpdateCache[key] = cache
		favoriteStoreUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q favoriteStoreQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q favoriteStoreQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for favorite_stores")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for favorite_stores")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FavoriteStoreSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FavoriteStoreSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), favoriteStorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `favorite_stores` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, favoriteStorePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in favoriteStore slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all favoriteStore")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *FavoriteStore) UpsertG(ctx context.Context, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns)
}

var mySQLFavoriteStoreUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FavoriteStore) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no favorite_stores provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(favoriteStoreColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLFavoriteStoreUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	favoriteStoreUpsertCacheMut.RLock()
	cache, cached := favoriteStoreUpsertCache[key]
	favoriteStoreUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			favoriteStoreAllColumns,
			favoriteStoreColumnsWithDefault,
			favoriteStoreColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			favoriteStoreAllColumns,
			favoriteStorePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert favorite_stores, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`favorite_stores`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `favorite_stores` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for favorite_stores")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(favoriteStoreType, favoriteStoreMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for favorite_stores")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for favorite_stores")
	}

CacheNoHooks:
	if !cached {
		favoriteStoreUpsertCacheMut.Lock()
		favoriteStoreUpsertCache[key] = cache
		favoriteStoreUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single FavoriteStore record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *FavoriteStore) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single FavoriteStore record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FavoriteStore) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FavoriteStore provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), favoriteStorePrimaryKeyMapping)
	sql := "DELETE FROM `favorite_stores` WHERE `customer_id`=? AND `store_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from favorite_stores")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for favorite_stores")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q favoriteStoreQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q favoriteStoreQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no favoriteStoreQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from favorite_stores")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for favorite_stores")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o FavoriteStoreSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FavoriteStoreSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(favoriteStoreBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), favoriteStorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `favorite_stores` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, favoriteStorePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from favoriteStore slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for favorite_stores")
	}

	if len(favoriteStoreAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *FavoriteStore) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no FavoriteStore provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FavoriteStore) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFavoriteStore(ctx, exec, o.CustomerID, o.StoreID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FavoriteStoreSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty FavoriteStoreSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FavoriteStoreSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FavoriteStoreSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), favoriteStorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `favorite_stores`.* FROM `favorite_stores` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, favoriteStorePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FavoriteStoreSlice")
	}

	*o = slice

	return nil
}

// FavoriteStoreExistsG checks if the FavoriteStore row exists.
func FavoriteStoreExistsG(ctx context.Context, customerID int, storeID int) (bool, error) {
	return FavoriteStoreExists(ctx, boil.GetContextDB(), customerID, storeID)
}

// FavoriteStoreExists checks if the FavoriteStore row exists.
func FavoriteStoreExists(ctx context.Context, exec boil.ContextExecutor, customerID int, storeID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `favorite_stores` where `customer_id`=? AND `store_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, customerID, storeID)
	}
	row := exec.QueryRowContext(ctx, sql, customerID, storeID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if favorite_stores exists")
	}

	return exists, nil
}

// Exists checks if the FavoriteStore row exists.
func (o *FavoriteStore) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FavoriteStoreExists(ctx, exec, o.CustomerID, o.StoreID)
}
