// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// StoreStaff is an object representing the database table.
type StoreStaff struct {
	StaffID       int       `boil:"staff_id" json:"staff_id" toml:"staff_id" yaml:"staff_id"`
	StoreID       int       `boil:"store_id" json:"store_id" toml:"store_id" yaml:"store_id"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedBy     null.Int  `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	CreatedByType string    `boil:"created_by_type" json:"created_by_type" toml:"created_by_type" yaml:"created_by_type"`
	UpdatedBy     null.Int  `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	UpdatedByType string    `boil:"updated_by_type" json:"updated_by_type" toml:"updated_by_type" yaml:"updated_by_type"`

	R *storeStaffR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L storeStaffL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StoreStaffColumns = struct {
	StaffID       string
	StoreID       string
	CreatedAt     string
	UpdatedAt     string
	CreatedBy     string
	CreatedByType string
	UpdatedBy     string
	UpdatedByType string
}{
	StaffID:       "staff_id",
	StoreID:       "store_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	CreatedBy:     "created_by",
	CreatedByType: "created_by_type",
	UpdatedBy:     "updated_by",
	UpdatedByType: "updated_by_type",
}

var StoreStaffTableColumns = struct {
	StaffID       string
	StoreID       string
	CreatedAt     string
	UpdatedAt     string
	CreatedBy     string
	CreatedByType string
	UpdatedBy     string
	UpdatedByType string
}{
	StaffID:       "store_staffs.staff_id",
	StoreID:       "store_staffs.store_id",
	CreatedAt:     "store_staffs.created_at",
	UpdatedAt:     "store_staffs.updated_at",
	CreatedBy:     "store_staffs.created_by",
	CreatedByType: "store_staffs.created_by_type",
	UpdatedBy:     "store_staffs.updated_by",
	UpdatedByType: "store_staffs.updated_by_type",
}

// Generated where

var StoreStaffWhere = struct {
	StaffID       whereHelperint
	StoreID       whereHelperint
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	CreatedBy     whereHelpernull_Int
	CreatedByType whereHelperstring
	UpdatedBy     whereHelpernull_Int
	UpdatedByType whereHelperstring
}{
	StaffID:       whereHelperint{field: "`store_staffs`.`staff_id`"},
	StoreID:       whereHelperint{field: "`store_staffs`.`store_id`"},
	CreatedAt:     whereHelpertime_Time{field: "`store_staffs`.`created_at`"},
	UpdatedAt:     whereHelpertime_Time{field: "`store_staffs`.`updated_at`"},
	CreatedBy:     whereHelpernull_Int{field: "`store_staffs`.`created_by`"},
	CreatedByType: whereHelperstring{field: "`store_staffs`.`created_by_type`"},
	UpdatedBy:     whereHelpernull_Int{field: "`store_staffs`.`updated_by`"},
	UpdatedByType: whereHelperstring{field: "`store_staffs`.`updated_by_type`"},
}

// StoreStaffRels is where relationship names are stored.
var StoreStaffRels = struct {
	Staff string
	Store string
}{
	Staff: "Staff",
	Store: "Store",
}

// storeStaffR is where relationships are stored.
type storeStaffR struct {
	Staff *Staff `boil:"Staff" json:"Staff" toml:"Staff" yaml:"Staff"`
	Store *Store `boil:"Store" json:"Store" toml:"Store" yaml:"Store"`
}

// NewStruct creates a new relationship struct
func (*storeStaffR) NewStruct() *storeStaffR {
	return &storeStaffR{}
}

func (r *storeStaffR) GetStaff() *Staff {
	if r == nil {
		return nil
	}
	return r.Staff
}

func (r *storeStaffR) GetStore() *Store {
	if r == nil {
		return nil
	}
	return r.Store
}

// storeStaffL is where Load methods for each relationship are stored.
type storeStaffL struct{}

var (
	storeStaffAllColumns            = []string{"staff_id", "store_id", "created_at", "updated_at", "created_by", "created_by_type", "updated_by", "updated_by_type"}
	storeStaffColumnsWithoutDefault = []string{"staff_id", "store_id"}
	storeStaffColumnsWithDefault    = []string{"created_at", "updated_at", "created_by", "created_by_type", "updated_by", "updated_by_type"}
	storeStaffPrimaryKeyColumns     = []string{"staff_id", "store_id"}
	storeStaffGeneratedColumns      = []string{}
)

type (
	// StoreStaffSlice is an alias for a slice of pointers to StoreStaff.
	// This should almost always be used instead of []StoreStaff.
	StoreStaffSlice []*StoreStaff
	// StoreStaffHook is the signature for custom StoreStaff hook methods
	StoreStaffHook func(context.Context, boil.ContextExecutor, *StoreStaff) error

	storeStaffQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	storeStaffType                 = reflect.TypeOf(&StoreStaff{})
	storeStaffMapping              = queries.MakeStructMapping(storeStaffType)
	storeStaffPrimaryKeyMapping, _ = queries.BindMapping(storeStaffType, storeStaffMapping, storeStaffPrimaryKeyColumns)
	storeStaffInsertCacheMut       sync.RWMutex
	storeStaffInsertCache          = make(map[string]insertCache)
	storeStaffUpdateCacheMut       sync.RWMutex
	storeStaffUpdateCache          = make(map[string]updateCache)
	storeStaffUpsertCacheMut       sync.RWMutex
	storeStaffUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var storeStaffAfterSelectHooks []StoreStaffHook

var storeStaffBeforeInsertHooks []StoreStaffHook
var storeStaffAfterInsertHooks []StoreStaffHook

var storeStaffBeforeUpdateHooks []StoreStaffHook
var storeStaffAfterUpdateHooks []StoreStaffHook

var storeStaffBeforeDeleteHooks []StoreStaffHook
var storeStaffAfterDeleteHooks []StoreStaffHook

var storeStaffBeforeUpsertHooks []StoreStaffHook
var storeStaffAfterUpsertHooks []StoreStaffHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StoreStaff) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *StoreStaff) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *StoreStaff) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *StoreStaff) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *StoreStaff) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *StoreStaff) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *StoreStaff) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *StoreStaff) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *StoreStaff) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range storeStaffAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStoreStaffHook registers your hook function for all future operations.
func AddStoreStaffHook(hookPoint boil.HookPoint, storeStaffHook StoreStaffHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		storeStaffAfterSelectHooks = append(storeStaffAfterSelectHooks, storeStaffHook)
	case boil.BeforeInsertHook:
		storeStaffBeforeInsertHooks = append(storeStaffBeforeInsertHooks, storeStaffHook)
	case boil.AfterInsertHook:
		storeStaffAfterInsertHooks = append(storeStaffAfterInsertHooks, storeStaffHook)
	case boil.BeforeUpdateHook:
		storeStaffBeforeUpdateHooks = append(storeStaffBeforeUpdateHooks, storeStaffHook)
	case boil.AfterUpdateHook:
		storeStaffAfterUpdateHooks = append(storeStaffAfterUpdateHooks, storeStaffHook)
	case boil.BeforeDeleteHook:
		storeStaffBeforeDeleteHooks = append(storeStaffBeforeDeleteHooks, storeStaffHook)
	case boil.AfterDeleteHook:
		storeStaffAfterDeleteHooks = append(storeStaffAfterDeleteHooks, storeStaffHook)
	case boil.BeforeUpsertHook:
		storeStaffBeforeUpsertHooks = append(storeStaffBeforeUpsertHooks, storeStaffHook)
	case boil.AfterUpsertHook:
		storeStaffAfterUpsertHooks = append(storeStaffAfterUpsertHooks, storeStaffHook)
	}
}

// OneG returns a single storeStaff record from the query using the global executor.
func (q storeStaffQuery) OneG(ctx context.Context) (*StoreStaff, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single storeStaff record from the query.
func (q storeStaffQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StoreStaff, error) {
	o := &StoreStaff{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for store_staffs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all StoreStaff records from the query using the global executor.
func (q storeStaffQuery) AllG(ctx context.Context) (StoreStaffSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all StoreStaff records from the query.
func (q storeStaffQuery) All(ctx context.Context, exec boil.ContextExecutor) (StoreStaffSlice, error) {
	var o []*StoreStaff

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to StoreStaff slice")
	}

	if len(storeStaffAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all StoreStaff records in the query using the global executor
func (q storeStaffQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all StoreStaff records in the query.
func (q storeStaffQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count store_staffs rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q storeStaffQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q storeStaffQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if store_staffs exists")
	}

	return count > 0, nil
}

// Staff pointed to by the foreign key.
func (o *StoreStaff) Staff(mods ...qm.QueryMod) staffQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`staff_id` = ?", o.StaffID),
	}

	queryMods = append(queryMods, mods...)

	return Staffs(queryMods...)
}

// Store pointed to by the foreign key.
func (o *StoreStaff) Store(mods ...qm.QueryMod) storeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`store_id` = ?", o.StoreID),
	}

	queryMods = append(queryMods, mods...)

	return Stores(queryMods...)
}

// LoadStaff allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (storeStaffL) LoadStaff(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStoreStaff interface{}, mods queries.Applicator) error {
	var slice []*StoreStaff
	var object *StoreStaff

	if singular {
		var ok bool
		object, ok = maybeStoreStaff.(*StoreStaff)
		if !ok {
			object = new(StoreStaff)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStoreStaff)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStoreStaff))
			}
		}
	} else {
		s, ok := maybeStoreStaff.(*[]*StoreStaff)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStoreStaff)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStoreStaff))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &storeStaffR{}
		}
		args = append(args, object.StaffID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &storeStaffR{}
			}

			for _, a := range args {
				if a == obj.StaffID {
					continue Outer
				}
			}

			args = append(args, obj.StaffID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`staffs`),
		qm.WhereIn(`staffs.staff_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Staff")
	}

	var resultSlice []*Staff
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Staff")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for staffs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for staffs")
	}

	if len(staffAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Staff = foreign
		if foreign.R == nil {
			foreign.R = &staffR{}
		}
		foreign.R.StoreStaffs = append(foreign.R.StoreStaffs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StaffID == foreign.StaffID {
				local.R.Staff = foreign
				if foreign.R == nil {
					foreign.R = &staffR{}
				}
				foreign.R.StoreStaffs = append(foreign.R.StoreStaffs, local)
				break
			}
		}
	}

	return nil
}

// LoadStore allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (storeStaffL) LoadStore(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStoreStaff interface{}, mods queries.Applicator) error {
	var slice []*StoreStaff
	var object *StoreStaff

	if singular {
		var ok bool
		object, ok = maybeStoreStaff.(*StoreStaff)
		if !ok {
			object = new(StoreStaff)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStoreStaff)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStoreStaff))
			}
		}
	} else {
		s, ok := maybeStoreStaff.(*[]*StoreStaff)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStoreStaff)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStoreStaff))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &storeStaffR{}
		}
		args = append(args, object.StoreID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &storeStaffR{}
			}

			for _, a := range args {
				if a == obj.StoreID {
					continue Outer
				}
			}

			args = append(args, obj.StoreID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`stores`),
		qm.WhereIn(`stores.store_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Store")
	}

	var resultSlice []*Store
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Store")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for stores")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for stores")
	}

	if len(storeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Store = foreign
		if foreign.R == nil {
			foreign.R = &storeR{}
		}
		foreign.R.StoreStaffs = append(foreign.R.StoreStaffs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StoreID == foreign.StoreID {
				local.R.Store = foreign
				if foreign.R == nil {
					foreign.R = &storeR{}
				}
				foreign.R.StoreStaffs = append(foreign.R.StoreStaffs, local)
				break
			}
		}
	}

	return nil
}

// SetStaffG of the storeStaff to the related item.
// Sets o.R.Staff to related.
// Adds o to related.R.StoreStaffs.
// Uses the global database handle.
func (o *StoreStaff) SetStaffG(ctx context.Context, insert bool, related *Staff) error {
	return o.SetStaff(ctx, boil.GetContextDB(), insert, related)
}

// SetStaff of the storeStaff to the related item.
// Sets o.R.Staff to related.
// Adds o to related.R.StoreStaffs.
func (o *StoreStaff) SetStaff(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Staff) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `store_staffs` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"staff_id"}),
		strmangle.WhereClause("`", "`", 0, storeStaffPrimaryKeyColumns),
	)
	values := []interface{}{related.StaffID, o.StaffID, o.StoreID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StaffID = related.StaffID
	if o.R == nil {
		o.R = &storeStaffR{
			Staff: related,
		}
	} else {
		o.R.Staff = related
	}

	if related.R == nil {
		related.R = &staffR{
			StoreStaffs: StoreStaffSlice{o},
		}
	} else {
		related.R.StoreStaffs = append(related.R.StoreStaffs, o)
	}

	return nil
}

// SetStoreG of the storeStaff to the related item.
// Sets o.R.Store to related.
// Adds o to related.R.StoreStaffs.
// Uses the global database handle.
func (o *StoreStaff) SetStoreG(ctx context.Context, insert bool, related *Store) error {
	return o.SetStore(ctx, boil.GetContextDB(), insert, related)
}

// SetStore of the storeStaff to the related item.
// Sets o.R.Store to related.
// Adds o to related.R.StoreStaffs.
func (o *StoreStaff) SetStore(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Store) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `store_staffs` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"store_id"}),
		strmangle.WhereClause("`", "`", 0, storeStaffPrimaryKeyColumns),
	)
	values := []interface{}{related.StoreID, o.StaffID, o.StoreID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StoreID = related.StoreID
	if o.R == nil {
		o.R = &storeStaffR{
			Store: related,
		}
	} else {
		o.R.Store = related
	}

	if related.R == nil {
		related.R = &storeR{
			StoreStaffs: StoreStaffSlice{o},
		}
	} else {
		related.R.StoreStaffs = append(related.R.StoreStaffs, o)
	}

	return nil
}

// StoreStaffs retrieves all the records using an executor.
func StoreStaffs(mods ...qm.QueryMod) storeStaffQuery {
	mods = append(mods, qm.From("`store_staffs`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`store_staffs`.*"})
	}

	return storeStaffQuery{q}
}

// FindStoreStaffG retrieves a single record by ID.
func FindStoreStaffG(ctx context.Context, staffID int, storeID int, selectCols ...string) (*StoreStaff, error) {
	return FindStoreStaff(ctx, boil.GetContextDB(), staffID, storeID, selectCols...)
}

// FindStoreStaff retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStoreStaff(ctx context.Context, exec boil.ContextExecutor, staffID int, storeID int, selectCols ...string) (*StoreStaff, error) {
	storeStaffObj := &StoreStaff{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `store_staffs` where `staff_id`=? AND `store_id`=?", sel,
	)

	q := queries.Raw(query, staffID, storeID)

	err := q.Bind(ctx, exec, storeStaffObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from store_staffs")
	}

	if err = storeStaffObj.doAfterSelectHooks(ctx, exec); err != nil {
		return storeStaffObj, err
	}

	return storeStaffObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *StoreStaff) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StoreStaff) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no store_staffs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(storeStaffColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	storeStaffInsertCacheMut.RLock()
	cache, cached := storeStaffInsertCache[key]
	storeStaffInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			storeStaffAllColumns,
			storeStaffColumnsWithDefault,
			storeStaffColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(storeStaffType, storeStaffMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(storeStaffType, storeStaffMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `store_staffs` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `store_staffs` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `store_staffs` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, storeStaffPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into store_staffs")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.StaffID,
		o.StoreID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for store_staffs")
	}

CacheNoHooks:
	if !cached {
		storeStaffInsertCacheMut.Lock()
		storeStaffInsertCache[key] = cache
		storeStaffInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single StoreStaff record using the global executor.
// See Update for more documentation.
func (o *StoreStaff) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the StoreStaff.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StoreStaff) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	storeStaffUpdateCacheMut.RLock()
	cache, cached := storeStaffUpdateCache[key]
	storeStaffUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			storeStaffAllColumns,
			storeStaffPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update store_staffs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `store_staffs` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, storeStaffPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(storeStaffType, storeStaffMapping, append(wl, storeStaffPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update store_staffs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for store_staffs")
	}

	if !cached {
		storeStaffUpdateCacheMut.Lock()
		storeStaffUpdateCache[key] = cache
		storeStaffUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q storeStaffQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q storeStaffQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for store_staffs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for store_staffs")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o StoreStaffSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StoreStaffSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storeStaffPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `store_staffs` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, storeStaffPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in storeStaff slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all storeStaff")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *StoreStaff) UpsertG(ctx context.Context, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns)
}

var mySQLStoreStaffUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StoreStaff) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no store_staffs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(storeStaffColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLStoreStaffUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	storeStaffUpsertCacheMut.RLock()
	cache, cached := storeStaffUpsertCache[key]
	storeStaffUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			storeStaffAllColumns,
			storeStaffColumnsWithDefault,
			storeStaffColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			storeStaffAllColumns,
			storeStaffPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert store_staffs, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`store_staffs`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `store_staffs` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(storeStaffType, storeStaffMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(storeStaffType, storeStaffMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for store_staffs")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(storeStaffType, storeStaffMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for store_staffs")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for store_staffs")
	}

CacheNoHooks:
	if !cached {
		storeStaffUpsertCacheMut.Lock()
		storeStaffUpsertCache[key] = cache
		storeStaffUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single StoreStaff record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *StoreStaff) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single StoreStaff record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StoreStaff) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no StoreStaff provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), storeStaffPrimaryKeyMapping)
	sql := "DELETE FROM `store_staffs` WHERE `staff_id`=? AND `store_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from store_staffs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for store_staffs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q storeStaffQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q storeStaffQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no storeStaffQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from store_staffs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for store_staffs")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o StoreStaffSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StoreStaffSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(storeStaffBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storeStaffPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `store_staffs` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, storeStaffPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from storeStaff slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for store_staffs")
	}

	if len(storeStaffAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *StoreStaff) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no StoreStaff provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StoreStaff) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStoreStaff(ctx, exec, o.StaffID, o.StoreID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StoreStaffSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty StoreStaffSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StoreStaffSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StoreStaffSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storeStaffPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `store_staffs`.* FROM `store_staffs` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, storeStaffPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in StoreStaffSlice")
	}

	*o = slice

	return nil
}

// StoreStaffExistsG checks if the StoreStaff row exists.
func StoreStaffExistsG(ctx context.Context, staffID int, storeID int) (bool, error) {
	return StoreStaffExists(ctx, boil.GetContextDB(), staffID, storeID)
}

// StoreStaffExists checks if the StoreStaff row exists.
func StoreStaffExists(ctx context.Context, exec boil.ContextExecutor, staffID int, storeID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `store_staffs` where `staff_id`=? AND `store_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, staffID, storeID)
	}
	row := exec.QueryRowContext(ctx, sql, staffID, storeID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if store_staffs exists")
	}

	return exists, nil
}

// Exists checks if the StoreStaff row exists.
func (o *StoreStaff) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return StoreStaffExists(ctx, exec, o.StaffID, o.StoreID)
}
